apiVersion: v1
metadata:
  name: nginx-svc
kind: Service
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 3000
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: nginx-html-vol
      volumes:
        - name: nginx-html-vol
          persistentVolumeClaim:
            claimName: nginx-pvc

